create temporary table game_challenge_seed_rows (
  source_id integer primary key,
  challenge text not null,
  category text not null,
  difficulty integer not null check (difficulty between 1 and 5)
) on commit drop;

insert into game_challenge_seed_rows (source_id, challenge, category, difficulty)
values
  (1, $challenge_text$Call an ex or old crush and ask them to settle a ridiculous debate: is cereal a soup?$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 5),
  (2, $challenge_text$Voice-note a close friend using a dramatic movie-trailer voice and ask what they are doing tonight.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 3),
  (3, $challenge_text$Call someone you have not spoken to in at least six months and sing Happy Birthday, even if it is not their birthday.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 4),
  (4, $challenge_text$Text the fifth person in your recent chats: “I have made my decision.” Give no explanation for five minutes.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 4),
  (5, $challenge_text$Call a sibling or close friend and seriously ask whether they think you could survive in the wilderness.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 3),
  (6, $challenge_text$Send a voice note to a friend pretending you are accepting an award for being their best friend.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 3),
  (7, $challenge_text$Call a friend and speak only in questions for one full minute.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 4),
  (8, $challenge_text$Text someone: “Be honest—what animal has my personality?” and read their answer aloud.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 3),
  (9, $challenge_text$Call a close friend and try to convince them that you have started training for a professional sport of the group’s choice.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 4),
  (10, $challenge_text$Send your last-used emoji to three friends with no context.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 2),
  (11, $challenge_text$Call someone and ask them to rate your fake superhero name chosen by the group.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 3),
  (12, $challenge_text$Send a 20-second voice note describing your day as if it were breaking news.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 2),
  (13, $challenge_text$Text a close friend: “I need your honest opinion about something important,” then ask whether socks should be worn to bed.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 3),
  (14, $challenge_text$Call a friend and attempt to order an imaginary meal from them without laughing.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 4),
  (15, $challenge_text$Send a friend a sincere compliment followed by an unnecessarily dramatic farewell.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 2),
  (16, $challenge_text$Call someone and explain the rules of rock-paper-scissors as if they have never heard of it.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 3),
  (17, $challenge_text$Text the group-chosen contact a terrible original pickup line.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 4),
  (18, $challenge_text$Call a friend and ask them to guess which member of the group chose the challenge.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 3),
  (19, $challenge_text$Send a voice message in which every sentence rhymes for at least 30 seconds.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 4),
  (20, $challenge_text$Call someone and pretend you are conducting a customer-satisfaction survey about your friendship.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 4),
  (21, $challenge_text$Text a trusted friend: “I may need an alibi,” then immediately clarify that it is for losing at a game.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 3),
  (22, $challenge_text$Call a friend and ask them to give you a motivational speech before your next turn.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 2),
  (23, $challenge_text$Send a friend a voice note whispering an ordinary grocery list like it is classified information.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 3),
  (24, $challenge_text$Call someone and use a fake accent chosen by the group until they notice or one minute passes.$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 4),
  (25, $challenge_text$Text a friend a selfie with the caption: “New era. No questions at this time.”$challenge_text$, $challenge_category$Phone & Messages$challenge_category$, 4),
  (26, $challenge_text$Post a story poll asking: “Could I win a fight against one angry goose?”$challenge_text$, $challenge_category$Social Media$challenge_category$, 4),
  (27, $challenge_text$Post a story using a serious selfie and the caption: “I forgive everyone except whoever invented fitted sheets.”$challenge_text$, $challenge_category$Social Media$challenge_category$, 4),
  (28, $challenge_text$Post a ten-second story reviewing a glass of water like a luxury food critic.$challenge_text$, $challenge_category$Social Media$challenge_category$, 4),
  (29, $challenge_text$Change your profile bio for 15 minutes to a harmless title chosen by the group, such as “Regional Nap Champion.”$challenge_text$, $challenge_category$Social Media$challenge_category$, 5),
  (30, $challenge_text$Post a story asking followers to guess your secret talent, even if you do not have one.$challenge_text$, $challenge_category$Social Media$challenge_category$, 3),
  (31, $challenge_text$Post a close-up photo of a random household object and caption it like a celebrity announcement.$challenge_text$, $challenge_category$Social Media$challenge_category$, 3),
  (32, $challenge_text$Post a story saying: “Big announcement at 8,” then at 8 announce that you drank water.$challenge_text$, $challenge_category$Social Media$challenge_category$, 5),
  (33, $challenge_text$Post a story ranking three ordinary snacks with the seriousness of a sports analyst.$challenge_text$, $challenge_category$Social Media$challenge_category$, 3),
  (34, $challenge_text$Post a story of yourself walking in slow motion with dramatic music.$challenge_text$, $challenge_category$Social Media$challenge_category$, 4),
  (35, $challenge_text$Post a story asking: “What is the first word you think of when you see my face?”$challenge_text$, $challenge_category$Social Media$challenge_category$, 5),
  (36, $challenge_text$Post a story declaring one random object in the room your “employee of the month.”$challenge_text$, $challenge_category$Social Media$challenge_category$, 3),
  (37, $challenge_text$Post a 15-second fake apology video for always being too talented at something silly.$challenge_text$, $challenge_category$Social Media$challenge_category$, 5),
  (38, $challenge_text$Post a story with a blank background and the words: “Some of you owe me an explanation.”$challenge_text$, $challenge_category$Social Media$challenge_category$, 4),
  (39, $challenge_text$Post a story demonstrating a completely useless life hack invented by the group.$challenge_text$, $challenge_category$Social Media$challenge_category$, 4),
  (40, $challenge_text$Post a photo of your shoes and write a dramatic caption about the journey they have survived.$challenge_text$, $challenge_category$Social Media$challenge_category$, 3),
  (41, $challenge_text$Post a story asking followers to vote on a ridiculous new nickname for you.$challenge_text$, $challenge_category$Social Media$challenge_category$, 4),
  (42, $challenge_text$Post a story showing your best runway walk across the room.$challenge_text$, $challenge_category$Social Media$challenge_category$, 4),
  (43, $challenge_text$Post a serious motivational quote written by the group about snacks.$challenge_text$, $challenge_category$Social Media$challenge_category$, 4),
  (44, $challenge_text$Post a story saying: “Taking applications for a new best friend,” with three funny requirements.$challenge_text$, $challenge_category$Social Media$challenge_category$, 5),
  (45, $challenge_text$Post a story of yourself giving a weather report from inside the room.$challenge_text$, $challenge_category$Social Media$challenge_category$, 4),
  (46, $challenge_text$Post a photo of a spoon, fork, or cup and caption it: “We have been through so much together.”$challenge_text$, $challenge_category$Social Media$challenge_category$, 3),
  (47, $challenge_text$Post a story asking whether people think you could pull off being bald, famous, or both.$challenge_text$, $challenge_category$Social Media$challenge_category$, 4),
  (48, $challenge_text$Post a story with your most dramatic facial expression and no caption.$challenge_text$, $challenge_category$Social Media$challenge_category$, 4),
  (49, $challenge_text$Post a 20-second tutorial on how to do something everyone already knows, such as sitting down.$challenge_text$, $challenge_category$Social Media$challenge_category$, 5),
  (50, $challenge_text$Let the group choose a harmless photo from your camera roll for you to post to your story for ten minutes.$challenge_text$, $challenge_category$Social Media$challenge_category$, 5),
  (51, $challenge_text$Perform a one-minute breakup speech to a chair.$challenge_text$, $challenge_category$Performance$challenge_category$, 3),
  (52, $challenge_text$Give a serious campaign speech explaining why you should be elected leader of the room.$challenge_text$, $challenge_category$Performance$challenge_category$, 3),
  (53, $challenge_text$Act out your morning routine without speaking while the group guesses each step.$challenge_text$, $challenge_category$Performance$challenge_category$, 2),
  (54, $challenge_text$Sing the chorus of a song chosen by the group in an opera voice.$challenge_text$, $challenge_category$Performance$challenge_category$, 4),
  (55, $challenge_text$Do a 30-second stand-up comedy routine about someone in the room without insulting them.$challenge_text$, $challenge_category$Performance$challenge_category$, 4),
  (56, $challenge_text$Pretend to be a fitness instructor and lead the group through a ridiculous 45-second workout.$challenge_text$, $challenge_category$Performance$challenge_category$, 3),
  (57, $challenge_text$Give a passionate speech defending a food you actually dislike.$challenge_text$, $challenge_category$Performance$challenge_category$, 3),
  (58, $challenge_text$Reenact your most embarrassing harmless memory using only sound effects.$challenge_text$, $challenge_category$Performance$challenge_category$, 4),
  (59, $challenge_text$Perform a dramatic death scene caused by stepping on an imaginary Lego.$challenge_text$, $challenge_category$Performance$challenge_category$, 2),
  (60, $challenge_text$Impersonate another player until the group guesses who it is.$challenge_text$, $challenge_category$Performance$challenge_category$, 4),
  (61, $challenge_text$Read the ingredients on a food package like a romantic poem.$challenge_text$, $challenge_category$Performance$challenge_category$, 3),
  (62, $challenge_text$Pretend you are a celebrity being interviewed after winning an award for something ridiculous.$challenge_text$, $challenge_category$Performance$challenge_category$, 3),
  (63, $challenge_text$Make up and perform a national anthem for the room.$challenge_text$, $challenge_category$Performance$challenge_category$, 4),
  (64, $challenge_text$Act like a robot trying to understand human flirting for one minute.$challenge_text$, $challenge_category$Performance$challenge_category$, 4),
  (65, $challenge_text$Perform a soap-opera scene in which someone has stolen your last slice of pizza.$challenge_text$, $challenge_category$Performance$challenge_category$, 3),
  (66, $challenge_text$Give a courtroom closing argument proving that you are the funniest person present.$challenge_text$, $challenge_category$Performance$challenge_category$, 4),
  (67, $challenge_text$Perform a slow-motion action scene involving an invisible enemy.$challenge_text$, $challenge_category$Performance$challenge_category$, 3),
  (68, $challenge_text$Speak like a sports commentator during another player’s next turn.$challenge_text$, $challenge_category$Performance$challenge_category$, 3),
  (69, $challenge_text$Create and perform a 20-second jingle advertising yourself.$challenge_text$, $challenge_category$Performance$challenge_category$, 4),
  (70, $challenge_text$Pretend to be a strict teacher explaining why the group has failed at having fun.$challenge_text$, $challenge_category$Performance$challenge_category$, 3),
  (71, $challenge_text$Perform a dramatic reading of your most recent harmless text message.$challenge_text$, $challenge_category$Performance$challenge_category$, 3),
  (72, $challenge_text$Act like a confused tourist asking for directions to the kitchen.$challenge_text$, $challenge_category$Performance$challenge_category$, 2),
  (73, $challenge_text$Give an emotional farewell speech to an object the group selects.$challenge_text$, $challenge_category$Performance$challenge_category$, 3),
  (74, $challenge_text$Perform a one-minute nature documentary about another player.$challenge_text$, $challenge_category$Performance$challenge_category$, 4),
  (75, $challenge_text$Dance with complete confidence and no music for 30 seconds.$challenge_text$, $challenge_category$Performance$challenge_category$, 5),
  (76, $challenge_text$Do 20 push-ups, or 30 wall push-ups if needed.$challenge_text$, $challenge_category$Physical$challenge_category$, 4),
  (77, $challenge_text$Hold a plank for 45 seconds while answering rapid-fire questions.$challenge_text$, $challenge_category$Physical$challenge_category$, 4),
  (78, $challenge_text$Do 25 squats while naming a different celebrity on each one.$challenge_text$, $challenge_category$Physical$challenge_category$, 4),
  (79, $challenge_text$Balance a book on your head and walk across the room without using your hands.$challenge_text$, $challenge_category$Physical$challenge_category$, 3),
  (80, $challenge_text$Keep a balloon or crumpled paper ball in the air for one minute using only your elbows.$challenge_text$, $challenge_category$Physical$challenge_category$, 3),
  (81, $challenge_text$Do a wall sit for 45 seconds while singing.$challenge_text$, $challenge_category$Physical$challenge_category$, 4),
  (82, $challenge_text$Spin around ten times, then attempt to walk in a straight line.$challenge_text$, $challenge_category$Physical$challenge_category$, 3),
  (83, $challenge_text$Stand on one leg for one minute while the group tries to make you laugh.$challenge_text$, $challenge_category$Physical$challenge_category$, 3),
  (84, $challenge_text$Crab-walk across the room and back.$challenge_text$, $challenge_category$Physical$challenge_category$, 3),
  (85, $challenge_text$Do ten burpees while saying “I regret nothing” after each one.$challenge_text$, $challenge_category$Physical$challenge_category$, 5),
  (86, $challenge_text$Carry three small objects across the room without using your hands.$challenge_text$, $challenge_category$Physical$challenge_category$, 3),
  (87, $challenge_text$Do a full minute of jumping jacks while maintaining a serious face.$challenge_text$, $challenge_category$Physical$challenge_category$, 4),
  (88, $challenge_text$Touch your toes 20 times while naming foods alphabetically.$challenge_text$, $challenge_category$Physical$challenge_category$, 3),
  (89, $challenge_text$Walk backward around the room for one minute without bumping into anything.$challenge_text$, $challenge_category$Physical$challenge_category$, 3),
  (90, $challenge_text$Do your best moonwalk from one side of the room to the other.$challenge_text$, $challenge_category$Physical$challenge_category$, 3),
  (91, $challenge_text$Hold two harmless objects at arm’s length for one minute.$challenge_text$, $challenge_category$Physical$challenge_category$, 3),
  (92, $challenge_text$Do 15 lunges while complimenting a different player on each repetition.$challenge_text$, $challenge_category$Physical$challenge_category$, 4),
  (93, $challenge_text$Attempt five different dance moves in 30 seconds without repeating any.$challenge_text$, $challenge_category$Physical$challenge_category$, 3),
  (94, $challenge_text$Sit down on the floor and stand back up without using your hands.$challenge_text$, $challenge_category$Physical$challenge_category$, 3),
  (95, $challenge_text$Hop on one foot across the room while reciting the alphabet backward as far as you can.$challenge_text$, $challenge_category$Physical$challenge_category$, 4),
  (96, $challenge_text$Do 30 high knees while pretending you are escaping a very slow monster.$challenge_text$, $challenge_category$Physical$challenge_category$, 3),
  (97, $challenge_text$Balance a spoon on your nose for ten seconds.$challenge_text$, $challenge_category$Physical$challenge_category$, 2),
  (98, $challenge_text$Hold a squat for 30 seconds while giving a motivational speech.$challenge_text$, $challenge_category$Physical$challenge_category$, 4),
  (99, $challenge_text$Do an exaggerated runway walk while balancing an object on your head.$challenge_text$, $challenge_category$Physical$challenge_category$, 4),
  (100, $challenge_text$Attempt a harmless yoga pose chosen by the group and hold it for 20 seconds.$challenge_text$, $challenge_category$Physical$challenge_category$, 3),
  (101, $challenge_text$Let the group give you a new nickname that everyone must use for the next three rounds.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 4),
  (102, $challenge_text$Allow another player to style your hair for the next two rounds using only their hands.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 4),
  (103, $challenge_text$Give every person in the group a unique and sincere compliment.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 2),
  (104, $challenge_text$Let the group choose one word you must include in every sentence until your next turn.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 3),
  (105, $challenge_text$Switch seats with the person you know least and interview them for one minute.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 2),
  (106, $challenge_text$Let the group ask you five rapid-fire questions; answer immediately and honestly, but you may skip private topics.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 4),
  (107, $challenge_text$Choose another player and recreate a famous movie scene together with no preparation.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 4),
  (108, $challenge_text$Allow the group to choose your pose for a group photo.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 3),
  (109, $challenge_text$Make another player laugh within 30 seconds without touching them.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 3),
  (110, $challenge_text$Give a one-minute speech explaining why another player deserves a made-up award.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 3),
  (111, $challenge_text$Let the group select a harmless phrase you must shout whenever someone says your name for three rounds.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 4),
  (112, $challenge_text$Trade one visible accessory with another willing player for the next two rounds.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 2),
  (113, $challenge_text$Challenge another player to a ten-second staring contest; the loser must clap for the winner.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 2),
  (114, $challenge_text$Let each player contribute one sentence to a story that you must perform dramatically at the end.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 4),
  (115, $challenge_text$Give the person to your left a 30-second hype introduction like they are entering a boxing ring.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 3),
  (116, $challenge_text$Allow the group to choose a harmless celebrity or character you must imitate for one round.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 4),
  (117, $challenge_text$Try to guess everyone’s favorite snack; each wrong answer earns you one squat.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 4),
  (118, $challenge_text$Let another player choose three random words you must use in a romantic poem.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 4),
  (119, $challenge_text$Convince the group to buy an ordinary object in the room as if you are a salesperson.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 3),
  (120, $challenge_text$Let the group choose a song, then lip-sync it with maximum seriousness.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 4),
  (121, $challenge_text$Pair with another player and create a secret handshake in one minute.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 2),
  (122, $challenge_text$Let the group decide your signature dance move, which you must perform after every turn for two rounds.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 4),
  (123, $challenge_text$Give each player a funny but kind title, such as “Minister of Snacks.”$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 3),
  (124, $challenge_text$Let the group rearrange your sitting position using pillows or safe nearby objects for one round.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 3),
  (125, $challenge_text$Choose two players and host a 60-second fake talk show interview with them.$challenge_text$, $challenge_category$Group Interaction$challenge_category$, 4),
  (126, $challenge_text$Eat a cracker or small snack without using your hands.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 3),
  (127, $challenge_text$Taste a safe mystery snack chosen by the group while your eyes are closed and guess what it is.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 3),
  (128, $challenge_text$Drink a glass of water while maintaining intense eye contact with another player.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 3),
  (129, $challenge_text$Describe a common snack as if it costs $500 at a luxury restaurant.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 2),
  (130, $challenge_text$Make a tiny sandwich or snack combination chosen from three safe ingredients selected by the group.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 4),
  (131, $challenge_text$Eat one bite of food in exaggerated slow motion.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 2),
  (132, $challenge_text$Smell three safe items while blindfolded and correctly identify at least two.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 3),
  (133, $challenge_text$Give a one-minute cooking show using only ingredients or objects already in the room.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 3),
  (134, $challenge_text$Try to peel a banana, orange, or wrapped snack using only one hand.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 3),
  (135, $challenge_text$Take a sip of water after saying a dramatic toast to the group.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 2),
  (136, $challenge_text$Invent a fancy menu name for three ordinary foods in the room.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 2),
  (137, $challenge_text$Taste a tiny amount of a safe condiment chosen by the group.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 3),
  (138, $challenge_text$Feed yourself three bites of a safe snack using a spoon held in your non-dominant hand.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 3),
  (139, $challenge_text$Stack five small snack items or cups; if the tower falls, perform a victory dance anyway.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 3),
  (140, $challenge_text$Give a passionate review of the last thing you ate as if you are a famous critic.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 3),
  (141, $challenge_text$Create a new snack brand name, slogan, and 15-second commercial.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 4),
  (142, $challenge_text$Guess the flavor of a safe drink while holding your nose.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 3),
  (143, $challenge_text$Eat a small snack while pretending it is unbelievably spicy, even if it is not.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 2),
  (144, $challenge_text$Name ten foods in ten seconds without repeating or pausing.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 3),
  (145, $challenge_text$Balance a safe snack on your forehead and move it to your mouth without using your hands.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 4),
  (146, $challenge_text$Invent a ridiculous recipe using five ingredients named by the group.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 3),
  (147, $challenge_text$Serve water to another player as if they are royalty.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 2),
  (148, $challenge_text$Take one bite of a safe food combination selected by majority vote.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 4),
  (149, $challenge_text$Do a blind taste test between two similar safe snacks or drinks.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 3),
  (150, $challenge_text$Explain how to make toast as if it is the most difficult recipe in the world.$challenge_text$, $challenge_category$Food & Sensory$challenge_category$, 3),
  (151, $challenge_text$Write and perform a four-line rap about the person to your right.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 4),
  (152, $challenge_text$Draw a self-portrait with your non-dominant hand in 45 seconds and show everyone.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 3),
  (153, $challenge_text$Invent a conspiracy theory about an ordinary object in the room.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 3),
  (154, $challenge_text$Create a superhero identity, power, weakness, and catchphrase in one minute.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 3),
  (155, $challenge_text$Make up a bedtime story starring three members of the group.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 4),
  (156, $challenge_text$Draw another player without looking at the paper.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 4),
  (157, $challenge_text$Invent a new holiday and explain its traditions.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 3),
  (158, $challenge_text$Create a 30-second advertisement for a completely useless invention.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 3),
  (159, $challenge_text$Write a two-line love poem to your phone and read it aloud.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 3),
  (160, $challenge_text$Make a hat from safe nearby materials and wear it for two rounds.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 4),
  (161, $challenge_text$Invent a dance named after yourself and teach the group one move.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 4),
  (162, $challenge_text$Create a new handshake for greeting people from the future.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 3),
  (163, $challenge_text$Draw an animal from memory in 30 seconds; the group must guess it.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 2),
  (164, $challenge_text$Invent three absurd rules for an imaginary country where you are president.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 3),
  (165, $challenge_text$Create a dramatic movie title and plot based on the last photo in your camera roll.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 4),
  (166, $challenge_text$Write a short breakup note from one household object to another and read it aloud.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 3),
  (167, $challenge_text$Invent a new word, define it, and use it naturally three times before your next turn.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 3),
  (168, $challenge_text$Build a small sculpture from five safe objects in under one minute.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 3),
  (169, $challenge_text$Create a slogan for every player in the group.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 4),
  (170, $challenge_text$Make up a children’s song about losing at this game.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 4),
  (171, $challenge_text$Design an imaginary app that solves a ridiculous problem and pitch it to the group.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 3),
  (172, $challenge_text$Tell a 45-second story that includes a banana, a police officer, and a wedding.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 4),
  (173, $challenge_text$Create a new dance move using only your shoulders and name it.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 3),
  (174, $challenge_text$Draw the group as a superhero team and assign everyone a power.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 4),
  (175, $challenge_text$Invent a perfume or cologne inspired by the room and perform its commercial.$challenge_text$, $challenge_category$Creativity & Improv$challenge_category$, 4),
  (176, $challenge_text$Let the group choose a harmless sentence you must say to yourself in the mirror with complete confidence.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 4),
  (177, $challenge_text$Walk into another part of the room, return, and make a grand entrance as if everyone has been waiting for you.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 3),
  (178, $challenge_text$Show the group your best intentionally ugly selfie taken right now.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 4),
  (179, $challenge_text$Read the last three harmless items in your search history aloud.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 5),
  (180, $challenge_text$Let the group choose a harmless new lock-screen photo for the next 20 minutes.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 5),
  (181, $challenge_text$Reveal your most-used emoji and defend why it represents you.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 2),
  (182, $challenge_text$Speak in third person until your next turn.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 3),
  (183, $challenge_text$Wear your shirt, jacket, or hat in a harmless incorrect way for two rounds.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 3),
  (184, $challenge_text$Show the group the oldest harmless selfie currently on your phone.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 4),
  (185, $challenge_text$Let the group choose a song you must use as your entrance music for the next round.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 3),
  (186, $challenge_text$Give a sincere apology to your phone for dropping or ignoring it.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 3),
  (187, $challenge_text$Stand up and announce one harmless unpopular opinion, then defend it for 30 seconds.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 4),
  (188, $challenge_text$Let another player take one ridiculous but harmless photo of you.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 4),
  (189, $challenge_text$Show the group your current screen-time total or most-used app.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 5),
  (190, $challenge_text$Do your best flirtatious introduction to an inanimate object.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 4),
  (191, $challenge_text$Give yourself five over-the-top compliments without laughing.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 3),
  (192, $challenge_text$Let the group choose one harmless word you must temporarily add to your phone’s contact name for yourself.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 4),
  (193, $challenge_text$Attempt to make yourself cry on command for 30 seconds.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 4),
  (194, $challenge_text$Recreate your favorite emoji using only your face while the group guesses it.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 3),
  (195, $challenge_text$Let the group inspect your home screen for ten seconds, but you may hide private notifications first.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 5),
  (196, $challenge_text$Tell the group about a harmless lie you believed as a child.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 3),
  (197, $challenge_text$Speak with exaggerated confidence about a topic you know almost nothing about for one minute.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 4),
  (198, $challenge_text$Let the group choose a dramatic pose you must hold until your next turn.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 4),
  (199, $challenge_text$Describe your ideal date using only five words selected by the group.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 4),
  (200, $challenge_text$Allow the group to combine two previously completed challenges into one final challenge for you, provided both remain safe and harmless.$challenge_text$, $challenge_category$Awkward & Confidence$challenge_category$, 5);
insert into challenge_decks (id, name, description, enabled)
values (
  $deck_id$00000000-0000-0000-0000-000000000301$deck_id$,
  $deck_name$Baltimore Link Up Challenges$deck_name$,
  $deck_description$Challenge deck imported from game_challenges_200.csv.$deck_description$,
  true
)
on conflict (id) do update
set
  name = excluded.name,
  description = excluded.description,
  enabled = true,
  updated_at = now();

delete from challenges
where deck_id = $deck_id$00000000-0000-0000-0000-000000000301$deck_id$;

insert into challenges (
  id,
  deck_id,
  title,
  instructions,
  duration_seconds,
  success_criteria,
  props,
  enabled
)
select
  ($uuid_prefix$00000000-0000-0000-0001-$uuid_prefix$ || lpad((200000 + source_id)::text, 12, $zero$0$zero$))::uuid,
  $deck_id$00000000-0000-0000-0000-000000000301$deck_id$::uuid,
  category,
  challenge,
  case
    when difficulty <= 2 then 30
    when difficulty = 3 then 45
    else 60
  end,
  $success$The host confirms the challenge was attempted.$success$,
  jsonb_build_object(
    $source_id$sourceId$source_id$, source_id,
    $category$category$category$, category,
    $difficulty$difficulty$difficulty$, difficulty
  ),
  true
from game_challenge_seed_rows
order by source_id;

update challenge_decks
set enabled = false, updated_at = now()
where id <> $deck_id$00000000-0000-0000-0000-000000000301$deck_id$;

update challenges
set enabled = false, updated_at = now()
where deck_id is distinct from $deck_id$00000000-0000-0000-0000-000000000301$deck_id$;

update rooms
set
  settings = jsonb_set(
    settings,
    $settings_key_array${selectedChallengeDeckId}$settings_key_array$,
    to_jsonb($deck_id$00000000-0000-0000-0000-000000000301$deck_id$::text),
    true
  ),
  updated_at = now();
